### PR TITLE
Make `srfi` command line tool

### PR DESCRIPTION
**Pull request by lassik**

### CODE REVIEW

**Comment by lassik** [comment]
@arthurgleckler Do you prefer to merge something polished or something that's a decent foundation for more work?

The current code in this PR is approximately working. There are bound to be a few bugs, but I've tested all of the commands at one point, and am actively using many of them.

At the moment this requires Gauche, but there are cond-expands in place for adding Chibi and Chicken support, and hopefully with more to come.

I opted to re-use the `admin` subdirectory where you had your existing scripts. The `(admin private ...)` libraries are utility code that is not really SRFI specific. The `private` convention comes from R6RS programmers, and is used e.g. in `chez-srfi`.

**Comment by lassik** [comment]
Oh, to run the `srfi` command from a Unix shell, symlink `admin/wrapper/srfi-gosh` into some directory in your PATH under the filename `srfi`.

**Comment by arthurgleckler** [comment]
In progress is just fine.  Since this adds so many files, would you mind moving them under a directory like command/ or admin/command/ and adding a README there?

**Comment by lassik** [comment]
Sure. I converted a couple of your admin scripts to the new framework. Should I move them to the new directory as well?

**Comment by arthurgleckler** [comment]
On Sat, Sep 3, 2022, 10:44 AM lassik ***@***.***> wrote:

> Sure. I converted a couple of your admin scripts to the new framework.
> Should I move them to the new directory as well?
>

Sure!  Thanks.

>

**Comment by lassik** [comment]
OK, after quite a few tweaks I think the PR is now ready to be merged.

I have tested all commands, and they should work using the Gauche wrapper. Some commands also work in Chibi, but `os.chibi.scm` needs some more work. The Chibi version of `run-program-file-to-file` doesn't work. There may be other problems.

**Comment by lassik** [comment]
Please wait a while more after all... I managed to make a working Chicken egg of the thing.

**Comment by arthurgleckler** [comment]
No problem.  I'm behind on SRFIs, so I have plenty of work to do.

Thanks.

**Comment by arthurgleckler** [comment]
This is wonderful.  Thanks for putting this together.  I'm planning to replace a bunch of the Org code blocks I use for publishing drafts, etc., to use some of the subcommands.

I've been experimenting with it, and I found two places where `*TOP*` appears in what is supposed to be HTML output: in the output of `srfi abstract-html 233` and of `srfi rss`.  If you have a chance, would you take a look?  Otherwise, I'll get to it when I have a chance to dive in.

Thanks again.

**Comment by arthurgleckler** [comment]
Also, am I using the `toc` subcommand correctly: `srfi toc 226`?  I get "ERROR in "open-input-string": invalid type, expected String: values" under Chibi Scheme.

**Comment by arthurgleckler** [comment]
It works correctly under Gauche.

**Comment by lassik** [comment]
Thanks a lot for taking the time to look at it! I appreciate it.

Chibi emulates multiple values using a list. `toc` is hitting some problem with that.

BTW if you're using bash (or maybe zsh), `eval "$(srfi complete bash)"` enables tab completion for the subcommand.

**Pull request merged**
