### PR TITLE
Fix schemecomm link HTML

### PR DESCRIPTION
**Pull request by lassik**
Another go, this time for the template :)

### CODE REVIEW

**Comment by lassik** [comment]
(The previous PR was #5)

**Comment by lassik** [comment]
(The previous PR was #6 )

**Comment by arthurgleckler** [comment]
That's embarrassing.  Fixed.

**Comment by lassik** [comment]
No problem. I forgot the change to the `.html` file from this PR. I tried to generate it myself in MIT Scheme but didn't manage to figure out how to make it work.

**Pull request closed without merging**
