### PR TITLE
Add two library name commands

### PR DESCRIPTION
**Pull request by lassik**

### CODE REVIEW

**Comment by arthurgleckler** [comment]
Excellent.  Merged and pushed.

It generates `library-names.html` in the `srfi-common/` directory, but that's unused.  Did you intend to publish it at [registry.scheme.org](https://registry.scheme.org/)?

By the way, I just made it possible to search by `library-name` on the home page.

**Comment by lassik** [comment]
> It generates `library-names.html` in the `srfi-common/` directory, but that's unused. Did you intend to publish it at [registry.scheme.org](https://registry.scheme.org/)?

`library-names.html` isn't hosted anywhere at the moment. The names could go into the Registry, but since you're already tracking them in `srfi-data.scm` it's probably better not to duplicate the same information in two places. None of the registries currently are "mirrors" of tables stored elsewhere, though that's an interesting possibility. Do you think hosting the library name table on the SRFI site is too much of a maintenance burden?

> By the way, I just made it possible to search by `library-name` on the home page.

Great!

**Comment by arthurgleckler** [comment]
> library-names.html isn't hosted anywhere at the moment. The names could go into the Registry, but since you're already tracking them in srfi-data.scm it's probably better not to duplicate the same information in two places. None of the registries currently are "mirrors" of tables stored elsewhere, though that's an interesting possibility. Do you think hosting the library name table on the SRFI site is too much of a maintenance burden?

I don't see any need for the table on the SRFI site.  The data is already presented on the home page and on each SRFI's landing page, and it's in the S-expression database as well.  And it's now searchable.  If we were to host it on the SRFI site, I would want to make it match the look of the home page, which is a lot of work for my design-challenged self.

**Comment by arthurgleckler** [comment]
Let's keep it.  It will be just a little reminder, and if we find a good way to host it, we can.

**Pull request merged**
