### PR TITLE
More SRFI tool patches

### PR DESCRIPTION
**Pull request by lassik**

### CODE REVIEW

**Comment by arthurgleckler** [comment]
Merged and pushed.

Can you give me an example of a specific SRFI where you have the problem with Thunderbird?

**Comment by lassik** [comment]
Thanks!

E.g. `srfi compose-new-srfi 243`

**Comment by arthurgleckler** [comment]
Interesting.  That HTML is perfectly well-formed.  Even the W3C HTML Validator likes it once I wrap it in the right outer tags.  It doesn't even have unbalanced `p` elements.

Perhaps the `style` attribute I included in `<p style="margin-top: 3em;">SRFI Editor</p>` is the cause.  Would you please test it with that dropped?

**Comment by lassik** [comment]
My assumption was probably wrong.

I tried commenting out parts of the SXML and it still doesn't work; there isn't anything obviously wrong. The other mail templates use the same CSS and it works.

It may be that Chibi's HTML writer inserts newlines in some places, and either the Mac clipboard or Thunderbird's paste feature cannot handle newlines in the HTML. I recall I faced an issue like that earlier, which is why I disabled indentation of the HTML. I'll try to look into it tomorrow.

**Comment by lassik** [comment]
Confirmed, the problem was with the newlines. I'll send a PR.

**Pull request merged**
