### PR TITLE
Add "lucky" command

### PR DESCRIPTION
**Pull request by lassik**
Inspired by the Google Search "I'm feeling lucky" button.

### CODE REVIEW

**Comment by arthurgleckler** [comment]
This is silly, but fun.  It silently privileges the first match.  For example, `srfi lucky record` shows SRFI 9.

Merged and pushed, but I refactored it to use `srfi-search` first, and fixed an already existing warning about multiple definitions of `with-output-to-string`.

**Comment by lassik** [comment]
Yeah. It's half easter egg, half feature. But surprisingly often useful - as was the original, I guess. I now use it more often than the `search` command. If you can think of a better criterion than picking the earliest matching SRFI, please change it.

We could perhaps also add a command that browses a SRFI with the given library name.

Thanks for the fixes - good catches both.

**Comment by arthurgleckler** [comment]
On Sat, Oct 22, 2022 at 12:09 PM lassik ***@***.***> wrote:

> Yeah. It's half easter egg, half feature. But surprisingly often useful -
> as was the original, I guess. I now use it more often than the search
> command. If you can think of a better criterion than picking the earliest
> matching SRFI, please change it.
>
> I like it.

How about just displaying all the matches, then jumping to the first one?

**Comment by lassik** [comment]
`srfi search foo` shows all the matches. What do you mean by jumping in this context?

**Comment by arthurgleckler** [comment]
On Sat, Oct 22, 2022 at 1:04 PM lassik ***@***.***> wrote:

> srfi search foo shows all the matches. What do you mean by jumping in
> this context?
>
> Sorry, I mean just making lucky display all the matches on the terminal,
then send the browser to the first one.

**Comment by lassik** [comment]
Right. Sounds reasonable to me.

**Pull request merged**
